name: "Auto Float Version Tag Bump"
description: "Automatically increment version (X.Y) and tag the repository on push. Defaults to minor bump, or major if '#major' is in commit message."
author: "Srlion"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github_token:
    description: "GitHub token with repo access"
    required: true
outputs:
  new_tag:
    description: "The new version tag that was created"
